# Generated by Django 4.1.2 on 2022-10-23 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('correo', models.EmailField(max_length=200)),
                ('tema', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Contacto',
            },
        ),
    ]
